### ISSUE TITLE
Webpackのビルド負荷が異常に高い

### ISSUE THREAD

**Issue by Xeltica** [Groundpolis/Groundpolis#234]
ソース：https://github.com/syuilo/misskey/issues/6901 (解決済みとマークした箇所)

**Comment by mei23** [comment]
![image](https://user-images.githubusercontent.com/30769358/101282442-8cf26b00-3818-11eb-8a0d-3f69228915b8.png)

https://github.com/Groundpolis/Groundpolis/blob/f5707bcdd0e1490f5aefe0bf266ffb537a84cfb8/webpack.config.ts#L168
を消しただけで
12.62.1-gp-4.7.0 with max-old-space-size指定なし が 138sec でビルド成功するようになった

**Comment by Xeltica** [comment]
🙏 🙏 🙏 🙏 🙏

**Comment by Xeltica** [comment]
development環境での生産性向上のために使っているだけなので、productionではcacheしないようにするか

**Comment by mei23** [comment]
デフォルト値が
development: memory
production: disabled
みたいなんで、結局cacheオプションは指定しなくてOKみたい

https://webpack.js.org/configuration/other-options/#cache

**Comment by Xeltica** [comment]
メモリ1GB+スワップ1GB環境でやはりビルドできない（メモリ不足）

terser-webpack-plugin 5を使ったときに比べてメモリ消費量が爆上がりする

**Comment by Xeltica** [comment]
条件式間違えていただけ説がある
