### ISSUE TITLE
Koruriフォントを使う

### ISSUE THREAD

**Issue by Xeltica** [Groundpolis/Groundpolis#369]
https://github.com/remitocat/koruri をつかう

base.pugにて

```html
<link src="stylesheet" href="https://koruri.chillout.chat/koruri.css">
```

を追記し、style.scssに

```css
font-family: "Koruri", sans-serif;
```

を追加する（今游ゴシック体を指定している箇所を置き換える）

**Comment by remitocat** [comment]
https://koruri.remito.jp ですが，現在DNSエラーが出ているため，復旧作業が終わるまでしばらくお待ちください 🙏

**Comment by Xeltica** [comment]
フォントごとバンドルしてしまったほうが良さそうな気はする

**Comment by remitocat** [comment]
Milkeyのフォントはsubmoduleで管理してますし，そっちのほうが良いかもしれませんね

**Comment by Xeltica** [comment]
おまかせできたらしたい:pray:

**Comment by Xeltica** [comment]
とりあえずサブモジュールでフォントを組み込むのは #383 で取り掛かるとして、今回はissue説明の通り実装します
