### ISSUE TITLE
NodeInfoのnameを'groundpolis'とする

### ISSUE THREAD

**Issue by mei23** [Groundpolis/Groundpolis#403]
## 💡 Summary
Nodeinfo が `misskey` を名乗っている
https://github.com/Groundpolis/Groundpolis/blob/396b79cba979c7215288098fc107b28f92ec662f/src/server/nodeinfo.ts#L42

## 🙂 Expected Behavior
`groundpolis`

## ☹️ Actual Behavior
`misskey`

## 📝 Steps to Reproduce
1. Nodeinfo を確認

**Comment by Xeltica** [comment]
[メモ] 当時Misskeyのフォークであることから、NodeInfo上はMisskeyであることを明示したほうが都合が良いと判断し、misskeyを名乗るようにしていた。

都合が良いと思う理由がなかなか見つからないので変更する。

[経緯](https://groundpolis.app/notes/8uxo2k076o)
