### ISSUE TITLE
通知音オフの設定

### ISSUE THREAD

**Issue by Tsuion** [Groundpolis/Groundpolis#434]
通知音オフの設定をつけてほしい
音楽を聴きながらぐらぽりが見れない。。(切実)

**Comment by Xeltica** [comment]
@Tsuion  サウンド設定から変更できます

**Comment by Tsuion** [comment]
こちらの手違いでした。申し訳ありません。

音量を最小にしただけで、通知音の設定に“なし”という選択肢があることに気づきませんでした…💦
